CREATE PROCEDURE MEALTRAVEL_SEARCH(@MID INT = NULL, @M_NAME VARCHAR(20) = NULL, @TID INT = NULL)
AS
IF (@MID IS NULL AND @M_NAME IS NULL AND @TID IS NULL)
    SELECT * FROM MEALTRAVEL_VIEW;
ELSE IF (@MID IS NULL OR @M_NAME IS NULL OR @TID IS NULL)
    SELECT * FROM MEALTRAVEL_VIEW
    WHERE (MEAL_ID = @MID OR @MID IS NULL) AND (MEAL_NAME LIKE CONCAT('%',@M_NAME,'%') OR
     @M_NAME IS NULL) AND (@TID = TRAVEL_ID OR @TID IS NULL);
ELSE SELECT * FROM MEALTRAVEL_VIEW
    WHERE (MEAL_ID = @MID) AND (MEAL_NAME LIKE CONCAT('%',@M_NAME,'%')) AND (@TID = TRAVEL_ID);