-- BEFORE EXECUTING THIS PROCEDURE, MAKE SURE YOU HAVE ALREADY CREATED TICKETVIEW INTO THE DATABASE;
CREATE PROCEDURE TICKETSEARCH 
(
    @PID INT = NULL,
	@PSX VARCHAR(5) = NULL,
	@PFNAME VARCHAR(20) = NULL,
	@PLNAME VARCHAR(20) = NULL,
	@PHONE VARCHAR(13) = NULL,
	@PWAGON INT = NULL,
	@PCOUP INT = NULL,
	@PSEAT INT = NULL,
	@PMEAL BIT = NULL,
	@PSTARTTIME DATE = NULL,
	@PARRIVALTIME DATE = NULL,
	@STARTCITY VARCHAR(20) = NULL,
	@DESTCITY VARCHAR(20) = NULL
)
AS
IF (
	@PID IS NULL AND @PSX IS NULL AND @PFNAME IS NULL AND @PLNAME IS NULL AND @PHONE IS NULL AND @PWAGON IS NULL AND 
	@PCOUP IS NULL AND @PSEAT IS NULL AND @PMEAL IS NULL AND @PSTARTTIME IS NULL AND 
	@PARRIVALTIME IS NULL AND @STARTCITY IS NULL AND @DESTCITY IS NULL
)
SELECT * FROM TICKETVIEW;
ELSE IF (
	@PID IS NULL OR @PSX IS NULL OR @PFNAME IS NULL OR @PLNAME IS NULL OR @PHONE IS NULL OR @PWAGON IS NULL OR 
	@PCOUP IS NULL OR @PSEAT IS NULL OR @PMEAL IS NULL OR @PSTARTTIME IS NULL OR 
	@PARRIVALTIME IS NULL OR @STARTCITY IS NULL OR @DESTCITY IS NULL
)
SELECT * FROM TICKETVIEW
WHERE (@PID = PASSENGER_ID OR @PID IS NULL) AND (SX LIKE CONCAT('%',@PSX,'%') OR @PSX IS NULL) AND (FNAME LIKE CONCAT('%',@PFNAME,'%') OR @PFNAME IS NULL) AND
(LNAME LIKE CONCAT('%',@PLNAME,'%') OR @PLNAME IS NULL) AND (PHONE LIKE CONCAT('%',@PHONE,'%') OR @PHONE IS NULL) AND (WAGON_NUMBER = @PWAGON OR @PWAGON IS NULL) AND 
(COUPE_NUMBER = @PCOUP OR @PCOUP IS NULL) AND (SEAT_NUMBER = @PSEAT OR @PSEAT IS NULL) AND (MEAL_RESERVE = @PMEAL OR @PMEAL IS NULL) AND (@PSTARTTIME = (SELECT CONVERT(VARCHAR(10), START_TIME, 111)) OR @PSTARTTIME IS NULL) AND 
(@PARRIVALTIME = (SELECT CONVERT(VARCHAR(10), ARRIVAL_TIME, 111)) OR @PARRIVALTIME IS NULL) AND (STARTPOINT LIKE CONCAT('%',@STARTCITY,'%') OR @STARTCITY IS NULL) AND (DESTPOINT LIKE CONCAT('%',@DESTCITY,'%') OR @DESTCITY IS NULL);
ELSE SELECT * FROM TICKETVIEW
WHERE (@PID = PASSENGER_ID ) AND (SX LIKE CONCAT('%',@PSX,'%')) AND (FNAME LIKE CONCAT('%',@PFNAME,'%')) AND
(LNAME LIKE CONCAT('%',@PLNAME,'%')) AND (PHONE LIKE CONCAT('%',@PHONE,'%')) AND (WAGON_NUMBER = @PWAGON) AND 
(COUPE_NUMBER = @PCOUP) AND (SEAT_NUMBER = @PSEAT) AND (MEAL_RESERVE = @PMEAL) AND (@PSTARTTIME = (SELECT CONVERT(VARCHAR(10), START_TIME, 111))) AND 
(@PARRIVALTIME = (SELECT CONVERT(VARCHAR(10), ARRIVAL_TIME, 111))) AND (STARTPOINT LIKE CONCAT('%',@STARTCITY,'%')) AND (DESTPOINT LIKE CONCAT('%',@DESTCITY,'%'));