CREATE TABLE PASSENGER (
	img NVARCHAR(MAX),
	REG_DATE DATETIME NOT NULL,
	PASSENGER_ID INT PRIMARY KEY,
	PASSW NVARCHAR(MAX) NOT NULL,
	SX NVARCHAR(MAX) NOT NULL,
	FNAME NVARCHAR(MAX) NOT NULL,
	LNAME NVARCHAR(MAX) NOT NULL,
	BIRTH DATE NOT NULL,
	FATHER_NAME NVARCHAR(MAX) NOT NULL,
	PHONE VARCHAR(13) NOT NULL,
	ADDRESS NVARCHAR (MAX) NOT NULL
);
CREATE TABLE ORG(
	ORG_ID INT PRIMARY KEY,
	ORG_NAME NVARCHAR(MAX) NOT NULL
);
CREATE TABLE MODEL(
	MODEL_ID INT PRIMARY KEY,
	MODEL_NAME VARCHAR(10) NOT NULL UNIQUE
);
CREATE TABLE CITY(
	CITY_ID INT PRIMARY KEY,
	CITY_NAME NVARCHAR(MAX) NOT NULL
);
CREATE TABLE STATION(
	STATION_ID INT PRIMARY KEY,
	STATION_NAME NVARCHAR(MAX) NOT NULL
);
CREATE TABLE MEAL(
	MEAL_ID INT PRIMARY KEY,
	MEAL_NAME NVARCHAR(MAX) NOT NULL,
	MEAL_PRICE INT NOT NULL
);

CREATE TABLE TRAIN(
	TRAIN_ID INT PRIMARY KEY,
	TRAIN_DEGREE INT NOT NULL,
	COUP_CAPACITY INT NOT NULL,
	COUP_IN_WAGON INT NOT NULL,
	NUMOF_WAGON INT NOT NULL,
	ORG_ID INT NOT NULL,
	MODEL_ID INT,
	FOREIGN KEY (ORG_ID) REFERENCES ORG (ORG_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (MODEL_ID) REFERENCES MODEL (MODEL_ID)
	ON DELETE SET NULL ON UPDATE SET NULL
);

CREATE TABLE TRAVEL(
	TRAVEL_ID INT PRIMARY KEY,
	START_TIME DATETIME NOT NULL,
	ARRIVAL_TIME DATETIME NOT NULL,
	TRAIN_ID INT NOT NULL,
	START_ID INT NOT NULL,
	DEST_ID INT NOT NULL,
	BASE_PRICE INT NOT NULL,
	FOREIGN KEY (START_ID) REFERENCES CITY (CITY_ID),
	FOREIGN KEY (DEST_ID) REFERENCES CITY (CITY_ID),
	FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(TRAIN_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE TICKET (
	TRAVEL_ID INT NOT NULL,
	PASSENGER_ID INT NOT NULL,
	FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL (TRAVEL_ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID),
	CONSTRAINT TICKET_ID PRIMARY KEY (TRAVEL_ID,PASSENGER_ID),
	WAGON_NUMBER INT NOT NULL,
	COUPE_NUMBER INT NOT NULL,
	SEAT_NUMBER INT NOT NULL,
	MEAL_RESERVE BIT,
	IS_PAID BIT
);
CREATE TABLE MEAL_TRAVEL (
	MEAL_ID INT,
	TRAVEL_ID INT NOT NULL,
	FOREIGN KEY (MEAL_ID) REFERENCES MEAL (MEAL_ID),
	FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL (TRAVEL_ID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT MT_ID PRIMARY KEY (TRAVEL_ID,MEAL_ID)
);
CREATE TABLE TRAVEL_STATION(
	TRAVEL_ID INT NOT NULL,
	STATION_ID INT,
	FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL (TRAVEL_ID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (STATION_ID) REFERENCES STATION (STATION_ID),
	ENTRANCE DATETIME NOT NULL,
	QUIT DATETIME NOT NULL,
	CONSTRAINT TS_ID PRIMARY KEY (TRAVEL_ID,STATION_ID)
); 