CREATE FUNCTION MEALPRICECAL (@PID INT ,@TID INT)
RETURNS INT
AS
BEGIN
	DECLARE @RV INT = 0;
	IF (SELECT MEAL_RESERVE FROM TICKET WHERE PASSENGER_ID = @PID AND TRAVEL_ID = @TID) != 0
	AND (SELECT MEAL_ID FROM MEAL_TRAVEL WHERE TRAVEL_ID = @TID) IS NOT NULL
	SET @RV = (
		SELECT MEAL_PRICE FROM MEAL 
		JOIN (SELECT MEAL_ID FROM MEAL_TRAVEL WHERE TRAVEL_ID = @TID) M 
		ON M.MEAL_ID = MEAL.MEAL_ID
		);
	RETURN @RV;
END;
-- WARNING: IN ORDER TO MAKE THIS FUNCTION WORK RIGHT, MAKE SURE THERE IS NOT TWO MEALS FOR THE SAME TRAVEL
-- AT MEAL_TRAVEL TABLE