CREATE TRIGGER MEAL_DEL
ON MEAL
INSTEAD OF DELETE
AS
DECLARE C CURSOR
FOR (SELECT MEAL_ID FROM DELETED)
OPEN C
	DECLARE @TEMP INT;
	FETCH NEXT FROM C INTO @TEMP;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
	BEGIN TRANSACTION
		DELETE FROM MEAL_TRAVEL WHERE MEAL_ID = @TEMP;
		DELETE FROM MEAL WHERE MEAL_ID = @TEMP;
		FETCH NEXT FROM C INTO @TEMP;
		IF NOT EXISTS (SELECT * FROM MEAL M JOIN MEAL_TRAVEL T ON T.MEAL_ID = M.MEAL_ID WHERE M.MEAL_ID = @TEMP)
		COMMIT;
		ELSE ROLLBACK;
	END;
CLOSE C;
DEALLOCATE C;