CREATE TRIGGER MEALUP
ON MEAL
INSTEAD OF UPDATE
AS
DECLARE C CURSOR
FOR (SELECT MEAL_ID FROM INSERTED)
OPEN C
	DECLARE @T INT;
	FETCH NEXT FROM C INTO @T;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION
		IF @T NOT IN (SELECT MEAL_ID FROM MEAL)
		BEGIN
			DECLARE @PS INT;
			SET @PS = (SELECT S.MEAL_ID FROM MEAL S JOIN INSERTED I ON S.MEAL_NAME = I.MEAL_NAME
			WHERE I.MEAL_ID = @T);
			INSERT INTO MEAL SELECT * FROM INSERTED WHERE MEAL_ID = @T;
			UPDATE MEAL_TRAVEL SET MEAL_ID = @T WHERE MEAL_ID = @PS;
			DELETE FROM MEAL WHERE MEAL_ID = @PS;
		END;
		ELSE 
		BEGIN
		UPDATE MEAL SET MEAL_NAME = INSERTED.MEAL_NAME,MEAL_PRICE = INSERTED.MEAL_PRICE FROM INSERTED WHERE MEAL.MEAL_ID = @T; 
		FETCH NEXT FROM C INTO @T;
		END;
		IF EXISTS (SELECT * FROM MEAL M JOIN MEAL_TRAVEL T ON T.MEAL_ID = M.MEAL_ID WHERE M.MEAL_ID = @T)
			COMMIT;
		ELSE ROLLBACK;
	END;
CLOSE C;
DEALLOCATE C;