CREATE TRIGGER PASSENGER_DEL
ON PASSENGER
INSTEAD OF DELETE
AS
DECLARE C CURSOR
FOR (SELECT PASSENGER_ID FROM DELETED)
OPEN C
	DECLARE @TEMP INT;
	FETCH NEXT FROM C INTO @TEMP;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION
		DELETE FROM TICKET WHERE PASSENGER_ID = @TEMP;
		DELETE FROM PASSENGER WHERE PASSENGER_ID = @TEMP;
		FETCH NEXT FROM C INTO @TEMP;
		IF NOT EXISTS (SELECT * FROM PASSENGER P JOIN TICKET T ON P.PASSENGER_ID = T.PASSENGER_ID WHERE P.PASSENGER_ID = @TEMP)
		COMMIT;
		ELSE ROLLBACK;
	END;
CLOSE C;
DEALLOCATE C;
