CREATE TRIGGER STATION_DEL
ON STATION
INSTEAD OF DELETE
AS
DECLARE C CURSOR
FOR (SELECT STATION_ID FROM DELETED)
OPEN C
	DECLARE @TEMP INT;
	FETCH NEXT FROM C INTO @TEMP;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION
		DELETE FROM TRAVEL_STATION WHERE STATION_ID = @TEMP;
		DELETE FROM STATION WHERE STATION_ID = @TEMP;
		FETCH NEXT FROM C INTO @TEMP;
		IF NOT EXISTS (SELECT * FROM STATION S JOIN TRAVEL_STATION T ON T.STATION_ID = S.STATION_ID WHERE S.STATION_ID = @TEMP)
		COMMIT;
		ELSE ROLLBACK;
	END;
CLOSE C;
DEALLOCATE C;
