CREATE TRIGGER STATIONUP
ON STATION
INSTEAD OF UPDATE
AS
DECLARE C CURSOR
FOR (SELECT STATION_ID FROM INSERTED)
OPEN C
	DECLARE @T INT;
	FETCH NEXT FROM C INTO @T;
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF @T NOT IN (SELECT STATION_ID FROM STATION)
		BEGIN
			DECLARE @PS INT;
			SET @PS = (SELECT S.STATION_ID FROM STATION S JOIN INSERTED I ON S.STATION_NAME = I.STATION_NAME
			WHERE I.STATION_ID = @T);
			INSERT INTO STATION SELECT * FROM INSERTED WHERE STATION_ID = @T;
			UPDATE TRAVEL_STATION SET STATION_ID = @T WHERE STATION_ID = @PS;
			DELETE FROM STATION WHERE STATION_ID = @PS;
		END;
		ELSE 
		BEGIN
		UPDATE STATION SET STATION_NAME = INSERTED.STATION_NAME FROM INSERTED WHERE STATION.STATION_ID = @T; 
		FETCH NEXT FROM C INTO @T;
		END;
	END;
CLOSE C;
DEALLOCATE C;
DROP TRIGGER STATIONUP;