// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class MEAL_TRAVEL
    {
        [Key]
        public int MEAL_ID { get; set; }
        [Key]
        public int TRAVEL_ID { get; set; }

        [ForeignKey(nameof(MEAL_ID))]
        [InverseProperty("MEAL_TRAVEL")]
        public virtual MEAL MEAL { get; set; }
        [ForeignKey(nameof(TRAVEL_ID))]
        [InverseProperty("MEAL_TRAVEL")]
        public virtual TRAVEL TRAVEL { get; set; }
    }
}