// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication5.Models.DB
{
    public partial class MEALTRAVEL_SEARCHResult
    {
        public int MEAL_ID { get; set; }
        public int TRAVEL_ID { get; set; }
        public string MEAL_NAME { get; set; }
    }
}
