// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class MEAL
    {
        public MEAL()
        {
            MEAL_TRAVEL = new HashSet<MEAL_TRAVEL>();
        }

        [Key]
        public int MEAL_ID { get; set; }
        [Required]
        public string MEAL_NAME { get; set; }
        public int MEAL_PRICE { get; set; }

        [InverseProperty("MEAL")]
        public virtual ICollection<MEAL_TRAVEL> MEAL_TRAVEL { get; set; }
    }
}