// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class ORG
    {
        public ORG()
        {
            TRAIN = new HashSet<TRAIN>();
        }

        [Key]
        public int ORG_ID { get; set; }
        [Required]
        public string ORG_NAME { get; set; }

        [InverseProperty("ORG")]
        public virtual ICollection<TRAIN> TRAIN { get; set; }
    }
}