// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class PASSENGER
    {
        public PASSENGER()
        {
            TICKET = new HashSet<TICKET>();
        }

        public string img { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime REG_DATE { get; set; }
        [Key]
        public int PASSENGER_ID { get; set; }
        [Required]
        public string PASSW { get; set; }
        [Required]
        public string SX { get; set; }
        [Required]
        public string FNAME { get; set; }
        [Required]
        public string LNAME { get; set; }
        [Column(TypeName = "date")]
        public DateTime BIRTH { get; set; }
        [Required]
        public string FATHER_NAME { get; set; }
        [Required]
        [StringLength(13)]
        public string PHONE { get; set; }
        [Required]
        public string ADDRESS { get; set; }

        [InverseProperty("PASSENGER")]
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}