// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using WebApplication5.Models.DB;

namespace WebApplication5.Models.DB
{
    public partial class RailwayDBContext
    {

        [DbFunction("fullcap", "dbo")]
        public static int? fullcap(int? p_travel_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("MEALPRICECAL", "dbo")]
        public static int? MEALPRICECAL(int? PID, int? TID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("REMAINING", "dbo")]
        public static int? REMAINING(int? p_travel_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
