// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class STATION
    {
        public STATION()
        {
            TRAVEL_STATION = new HashSet<TRAVEL_STATION>();
        }

        [Key]
        public int STATION_ID { get; set; }
        [Required]
        public string STATION_NAME { get; set; }

        [InverseProperty("STATION")]
        public virtual ICollection<TRAVEL_STATION> TRAVEL_STATION { get; set; }
    }
}