// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class TICKET
    {
        [Key]
        public int TRAVEL_ID { get; set; }
        [Key]
        public int PASSENGER_ID { get; set; }
        public int WAGON_NUMBER { get; set; }
        public int? COUPE_NUMBER { get; set; }
        public int SEAT_NUMBER { get; set; }
        public bool? MEAL_RESERVE { get; set; }
        public bool? IS_PAID { get; set; }

        [ForeignKey(nameof(PASSENGER_ID))]
        [InverseProperty("TICKET")]
        public virtual PASSENGER PASSENGER { get; set; }
        [ForeignKey(nameof(TRAVEL_ID))]
        [InverseProperty("TICKET")]
        public virtual TRAVEL TRAVEL { get; set; }
    }
}