// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication5.Models.DB
{
    public partial class TICKETSEARCHResult
    {
        public int PASSENGER_ID { get; set; }
        public string SX { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public DateTime BIRTH { get; set; }
        public string FATHER_NAME { get; set; }
        public string PHONE { get; set; }
        public string ORG_NAME { get; set; }
        public int WAGON_NUMBER { get; set; }
        public int? COUPE_NUMBER { get; set; }
        public int SEAT_NUMBER { get; set; }
        public bool? MEAL_RESERVE { get; set; }
        public DateTime START_TIME { get; set; }
        public DateTime ARRIVAL_TIME { get; set; }
        public int BASE_PRICE { get; set; }
        public string startPoint { get; set; }
        public string destPoint { get; set; }
        public int? FINAL_PRICE { get; set; }
        public bool? IS_PAID { get; set; }
    }
}
