// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication5.Models.DB
{
    public partial class TrainSearchResult
    {
        public int TRAIN_ID { get; set; }
        public int TRAIN_DEGREE { get; set; }
        public int? COUP_CAPACITY { get; set; }
        public int? COUP_IN_WAGON { get; set; }
        public int NUMOF_WAGON { get; set; }
        public int ORG_ID { get; set; }
        public int? MODEL_ID { get; set; }
        public string org_name { get; set; }
        public string model_name { get; set; }
    }
}
