// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class TRAIN
    {
        public TRAIN()
        {
            TRAVEL = new HashSet<TRAVEL>();
        }

        [Key]
        public int TRAIN_ID { get; set; }
        public int TRAIN_DEGREE { get; set; }
        public int? COUP_CAPACITY { get; set; }
        public int? COUP_IN_WAGON { get; set; }
        public int NUMOF_WAGON { get; set; }
        public int ORG_ID { get; set; }
        public int? MODEL_ID { get; set; }

        [ForeignKey(nameof(MODEL_ID))]
        [InverseProperty("TRAIN")]
        public virtual MODEL MODEL { get; set; }
        [ForeignKey(nameof(ORG_ID))]
        [InverseProperty("TRAIN")]
        public virtual ORG ORG { get; set; }
        [InverseProperty("TRAIN")]
        public virtual ICollection<TRAVEL> TRAVEL { get; set; }
    }
}