// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class TRAVEL_STATION
    {
        [Key]
        public int TRAVEL_ID { get; set; }
        [Key]
        public int STATION_ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ENTRANCE { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime QUIT { get; set; }

        [ForeignKey(nameof(STATION_ID))]
        [InverseProperty("TRAVEL_STATION")]
        public virtual STATION STATION { get; set; }
        [ForeignKey(nameof(TRAVEL_ID))]
        [InverseProperty("TRAVEL_STATION")]
        public virtual TRAVEL TRAVEL { get; set; }
    }
}