// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    public partial class TRAVEL
    {
        public TRAVEL()
        {
            MEAL_TRAVEL = new HashSet<MEAL_TRAVEL>();
            TICKET = new HashSet<TICKET>();
            TRAVEL_STATION = new HashSet<TRAVEL_STATION>();
        }

        [Key]
        public int TRAVEL_ID { get; set; }
        public DateTime START_TIME { get; set; }
        public DateTime ARRIVAL_TIME { get; set; }
        public int TRAIN_ID { get; set; }
        public int START_ID { get; set; }
        public int DEST_ID { get; set; }
        public int BASE_PRICE { get; set; }

        [ForeignKey(nameof(DEST_ID))]
        [InverseProperty(nameof(CITY.TRAVELDEST))]
        public virtual CITY DEST { get; set; }
        [ForeignKey(nameof(START_ID))]
        [InverseProperty(nameof(CITY.TRAVELSTART))]
        public virtual CITY START { get; set; }
        [ForeignKey(nameof(TRAIN_ID))]
        [InverseProperty("TRAVEL")]
        public virtual TRAIN TRAIN { get; set; }
        [InverseProperty("TRAVEL")]
        public virtual ICollection<MEAL_TRAVEL> MEAL_TRAVEL { get; set; }
        [InverseProperty("TRAVEL")]
        public virtual ICollection<TICKET> TICKET { get; set; }
        [InverseProperty("TRAVEL")]
        public virtual ICollection<TRAVEL_STATION> TRAVEL_STATION { get; set; }
    }
}