// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication5.Models.DB
{
    public partial class TRAVELSTATION_MODResult
    {
        public int STATION_ID { get; set; }
        public string STATION_NAME { get; set; }
        public int TRAVEL_ID { get; set; }
    }
}
