// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Models.DB
{
    [Keyless]
    public partial class TRAVELFullView
    {
        public int TRAVEL_ID { get; set; }
        public DateTime START_TIME { get; set; }
        public DateTime ARRIVAL_TIME { get; set; }
        public int TRAIN_ID { get; set; }
        public int START_ID { get; set; }
        public int DEST_ID { get; set; }
        public int BASE_PRICE { get; set; }
        [Required]
        public string startPoint { get; set; }
        [Required]
        public string destPoint { get; set; }
        [Column("Full Capacity")]
        public int? Full_Capacity { get; set; }
        [Column("Remaining Capacity")]
        public int? Remaining_Capacity { get; set; }
    }
}